data_cfg:
  train_images_root: data/MORPH
  val_images_root: data/MORPH
  test_images_root: data/MORPH
  train_data_file: data/MORPH/data_list/ET_proto_train.txt
  val_data_file: data/MORPH/data_list/ET_proto_val.txt
  test_data_file: data/MORPH/data_list/ET_proto_val.txt
runner_cfg:
  model_cfg:
    prompt_learner_cfg:
      num_ranks: 101
